version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dogs
      MYSQL_USER: doguser
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth_gw:
    build:
      context: ./auth_gw
      dockerfile: Dockerfile
    container_name: auth_gw
    restart: always
    env_file:
      - ./auth_gw/.env
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dog_project-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth_gw:
        condition: service_started
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dog_project-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "5001:5000"
    depends_on:
      backend:
        condition: service_started
      auth_gw:
        condition: service_started
    volumes:
      - ./frontend:/app

volumes:
  mysql_data: